version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sms
      POSTGRES_USER: sms_user
      POSTGRES_PASSWORD: strongpass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sms_user -d sms"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - "15672:15672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  api:
    build: ./../app/api
    env_file: .env
    depends_on: [db, rabbit, redis]
    ports:
      - "8080:8080"

  worker:
    build: ./../app/worker
    env_file: .env
    depends_on: [db, rabbit, redis, api]

  scheduler:
    build: ./../app/scheduler
    env_file: .env
    depends_on: [db, rabbit, redis, api]

  web:
    build: ./../app/web
    env_file: .env
    depends_on: [api]

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - web_build:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: [web, api]

volumes:
  db_data:
  rabbit_data:
  redis_data:
  web_build:
